server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intergrate_data_center?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  messages:
    encoding: UTF-8
    basename: i18n/message

mybatis:
  type-aliases-package: com.idc.dao.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 将sql日志打印再控制台上
logging:
  file:
    path:
security:
  basic:
    enabled: false
  management.security.enabled=false
