package com.idc.common.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum IMFCodeTransEnum {
    code1("Current account balance", "经常账户余额"),
    code2("Financial account balance", "金融账户余额"),
    code3("Direct investment, net", "直接投资，净额"),
    code4("Financial derivatives, net", "金融衍生品，净值"),
    code5("Other investment, net", "其他投资，净额"),
    code6("Portfolio investment, net", "证券投资，净额"),
    code7("Change in reserves", "储备变化"),
    code8("Imports of goods and services", "货物和服务进口"),
    code9("Exports of goods and services", "货物和服务出口"),
    code10("External debt, total", "外债总额"),
    code11("External debt, total debt service", "外债，偿债总额"),
    code12("External debt, total debt service, interest", "外债，偿债总额，利息"),
    code13("External debt, total debt service, amortization", "外债，偿债总额，摊销"),
    code14("General government revenue", "一般政府收入"),
    code15("General government structural balance", "广义政府结构平衡"),
    code16("General government total expenditure", "一般政府总支出"),
    code17("General government net lending/borrowing", "一般政府净贷款/借款"),
    code18("General government primary net lending/borrowing", "一般政府主要净贷款/借款"),
    code19("General government gross debt", "一般政府总债务"),
    code20("General government net debt", "一般政府净债务"),
    code21("Employment", "就业"),
    code22("Population", "人口"),
    code23("Unemployment rate", "失业率"),
    code24("Output gap", "产出缺口"),
    code25("Gross domestic product, current prices", "国内生产总值，现价"),
    code26("Gross domestic product, deflator", "国内生产总值，平减指数"),
    code27("Gross domestic product corresponding to fiscal year, current prices", "对应财年的国内生产总值，现价"),
    code28("Gross domestic product, constant prices", "国内生产总值，不变价格"),
    code29("Gross domestic product per capita, current prices", "人均国内生产总值，现价"),
    code30("Gross domestic product per capita, constant prices", "人均国内生产总值，不变价格"),
    code31("Gross national savings", "国民总储蓄"),
    code32("Investment", "投资"),
    code33("Commodity Price Index includes both Fuel and Non-Fuel Price Indices", "商品价格指数包括燃料和非燃料价格指数"),
    code34("Aluminum, 99.5% minimum purity, LME spot price, CIF UK ports, US$ per metric tonne", "铝，最低纯度 99.5%，LME 现货价格，CIF 英国港口，美元每公吨"),
    code35("Bananas, Central American and Ecuador, FOB U.S. Ports, US$ per metric tonne", "香蕉，中美洲和厄瓜多尔，美国港口离岸价，美元每公吨"),
    code36("Barley, Canadian no.1 Western Barley, spot price, US$ per metric tonne", "大麦，加拿大排名第一的西部大麦，现货价格，美元每公吨"),
    code37("Beef, Australian and New Zealand 85% lean fores, FOB U.S. import price, US cents per pound", "牛肉，澳大利亚和新西兰 85% 瘦肉，FOB 美国进口价格，美分每磅"),
    code38("Commodity Beverage Price Index includes Coffee, Tea, and Cocoa", "商品饮料价格指数包括咖啡、茶和可可"),
    code39("Commodity Cereals Price Index includes Wheat, Maize (Corn), Rice, and Barley", "商品谷物价格指数包括小麦、玉米（玉米）、大米和大麦"),
    code40("Coal, Australian thermal coal, 1200- btu/pound, less than 1% sulfur, 14% ash, FOB Newcastle/Port Kembla, US$ per metric tonne", "煤炭，澳大利亚动力煤，1200- btu/磅，硫含量低于 1%，灰分 14%，FOB 纽卡斯尔/肯布拉港，美元每公吨"),
    code41("Coal, South African export price, US$ per metric tonne", "煤炭，南非出口价格，美元每公吨"),
    code42("Commodity Coal Price Index includes Australian and South African Coal", "商品煤炭价格指数包括澳大利亚和南非煤炭"),
    code43("Cocoa beans, International Cocoa Organization cash price, CIF US and European ports, US$ per metric tonne", "可可豆，国际可可组织现金价格，CIF 美国和欧洲港口，美元每公吨"),
    code44("Coffee, Other Mild Arabicas, International Coffee Organization New York cash price, ex-dock New York, US cents per pound", "咖啡，其他温和的阿拉比卡咖啡，纽约国际咖啡组织现金价格，纽约码头交货，美分每磅"),
    code45("Coffee, Robusta, International Coffee Organization New York cash price, ex-dock New York, US cents per pound", "咖啡，罗布斯塔，纽约国际咖啡组织现金价格，纽约码头前，美分每磅"),
    code46("Commodity Coffee Price Index includes Other Mild Arabicas and Robusta", "商品咖啡价格指数包括其他温和的阿拉比卡咖啡和罗布斯塔咖啡"),
    code47("Copper, grade A cathode, LME spot price, CIF European ports, US$ per metric tonne", "铜，A 级阴极，LME 现货价格，CIF 欧洲港口，美元每公吨"),
    code48("Cotton, Cotton Outlook `A Index`, Middling 1-3/32 inch staple, CIF Liverpool, US cents per pound", "棉花，棉花展望“A 指数”，中等 1-3/32 英寸短纤维，CIF 利物浦，每磅美分"),
    code49("Inflation, average consumer prices", "通货膨胀、平均消费价格"),
    code50("Inflation, end of period consumer prices", "通货膨胀，期末消费者价格"),
    code51("Commodity Food and Beverage Price Index includes Food and Beverage Price Indices", "商品食品和饮料价格指数包括食品和饮料价格指数"),
    code52("Fishmeal, Peru Fish meal/pellets 65% protein, CIF, US$ per metric tonne", "鱼粉，秘鲁 鱼粉/颗粒 65% 蛋白质，CIF，美元每公吨"),
    code53("Commodity Food Price Index includes Cereal, Vegetable Oils, Meat, Seafood, Sugar, Bananas, and Oranges Price Indices", "商品食品价格指数包括谷物、植物油、肉类、海鲜、糖、香蕉和橙子价格指数"),
    code54("Groundnuts (peanuts), 40/50 (40 to 50 count per ounce), cif Argentina, US$ per metric tonne", "花生（花生），40/50（每盎司 40 至 50 个），CIF 阿根廷，美元每公吨"),
    code55("Commodity Hardwood Price Index includes Hardwood Logs and Hardwood Sawn Price Indices", "商品硬木价格指数包括硬木原木和硬木锯材价格指数"),
    code56("Hides, Heavy native steers, over 53 pounds, wholesale dealer`s price, US cents per pound", "生皮，重型本地阉牛，超过 53 磅，批发商的价格，每磅美分"),
    code57("Commodity Industrial Inputs Price Index includes Agricultural Raw Materials and Metals Price Indices", "商品工业投入品价格指数包括农业原材料和金属价格指数"),
    code58("Iron Ore, China import Iron Ore Fines 62% FE spot (CFR Tianjin port) US$ per metric ton", "铁矿石，中国进口铁精粉62%FE现货（CFR天津港）美元/公吨"),
    code59("Lamb, frozen carcass Smithfield London, US cents per pound", "羊肉，冷冻胴体 Smithfield London，美分每磅"),
    code60("Lead, 99.97% pure, LME spot price, CIF European Ports, US$ per metric tonne", "铅，纯度 99.97%，伦敦金属交易所现货价格，CIF 欧洲港口，美元每公吨"),
    code61("Soft Logs, Average Export price from the U.S. for Douglas Fir, US$ per cubic meter", "花旗松美国软原木平均出口价格，美元每立方米"),
    code62("Hard Logs, Best quality Malaysian meranti, import price Japan, US$ per cubic meter", "硬原木，优质马来西亚柳桉，日本进口价，美元每立方米"),
    code63("Maize (corn), U.S. No.2 Yellow, FOB Gulf of Mexico, U.S. price, US$ per metric tonne", "玉米（玉米），美国 2 号黄玉米，墨西哥湾离岸价，美国价格，美元每公吨"),
    code64("Commodity Meat Price Index includes Beef, Lamb, Swine (pork), and Poultry Price Indices", "商品肉类价格指数包括牛肉、羊肉、猪（猪肉）和家禽价格指数"),
    code65("Commodity Metals Price Index includes Copper, Aluminum, Iron Ore, Tin, Nickel, Zinc, Lead, and Uranium Price Indices", "商品金属价格指数包括铜、铝、铁矿石、锡、镍、锌、铅和铀价格指数"),
    code66("Commodity Non-Fuel Price Index includes Food and Beverages and Industrial Inputs Price Indices", "商品非燃料价格指数包括食品和饮料以及工业投入品价格指数"),
    code67("Natural Gas, Russian Natural Gas border price in Germany, US$ per million metric British thermal units of gas", "天然气，俄罗斯天然气在德国的边界价格，每百万公制英国热单位天然气美元"),
    code68("Natural Gas, Indonesian Liquified Natural Gas in Japan, US$ per million metric British thermal units of liquid", "天然气，日本的印度尼西亚液化天然气，每百万公制英热液体单位美元"),
    code69("Natural Gas, Natural Gas spot price at the Henry Hub terminal in Louisiana, US$ per million metric British thermal units of gas", "天然气，路易斯安那州 Henry Hub 终端的天然气现货价格，每百万公制英热单位天然气"),
    code70("Commodity Natural Gas Price Index includes European, Japanese, and American Natural Gas Price Indices", "商品天然气价格指数包括欧洲、日本和美国的天然气价格指数"),
    code71("Nickel, melting grade, LME spot price, CIF European ports, US$ per metric tonne", "镍，熔化等级，LME 现货价格，CIF 欧洲港口，美元每公吨"),
    code72("Commodity Fuel (energy) Index includes Crude oil (petroleum), Natural Gas, and Coal Price Indices", "商品燃料（能源）指数包括原油（石油）、天然气和煤炭价格指数"),
    code73("Crude Oil (petroleum), simple average of three spot prices; Dated Brent, West Texas Intermediate, and the Dubai Fateh, US$ per barrel", "Crude Oil（石油），三种现货价格的简单平均；即期布伦特原油、西德克萨斯中质原油和迪拜法塔赫原油，美元/桶"),
    code74("Crude Oil (petroleum), Price index simple average of three spot prices (APSP); Dated Brent, West Texas Intermediate, and the Dubai Fateh", "Crude Oil（石油），三个现货价格的简单平均价格指数（APSP）；即日布伦特原油、西德克萨斯中质原油和迪拜法塔赫原油"),
    code75("Crude Oil (petroleum),  Dated Brent, light blend 38 API, fob U.K., US$ per barrel", "原油（石油），即日布伦特原油，轻质混合 38 API，英国离岸价，每桶美元"),
    code76("Oil; Dubai, medium, Fateh 32 API, fob Dubai Crude Oil (petroleum), Dubai Fateh Fateh 32 API, US$ per barrel", "油; Dubai, medium, Fateh 32 API, fob 迪拜原油（石油）, Dubai Fateh Fateh 32 API, 美元每桶"),
    code77("Crude Oil (petroleum), West Texas Intermediate 40 API, Midland Texas, US$ per barrel", "原油（石油），West Texas Intermediate 40 API，Midland Texas，美元每桶"),
    code78("Olive Oil, extra virgin less than 1% free fatty acid, ex-tanker price U.K., US$ per metric tonne", "游离脂肪酸含量低于 1% 的特级初榨橄榄油，英国油轮出厂价，美元每公吨"),
    code79("Oranges, miscellaneous oranges French import price, US$ per metric tonne", "橙子、杂橙法国进口价格，美元每公吨"),
    code80("Palm oil, Malaysia Palm Oil Futures (first contract forward) 4-5 percent FFA, US$ per metric tonne", "棕榈油，马来西亚棕榈油期货（第一份远期合约）4-5% FFA，美元每公吨"),
    code81("Swine (pork), 51-52% lean Hogs, U.S. price, US cents per pound", "猪（猪肉），51-52% 瘦肉猪，美国价格，每磅美分"),
    code82("Poultry (chicken), Whole bird spot price, Georgia docks, US cents per pound", "家禽（鸡），整鸟现货价格，佐治亚码头，每磅美分"),
    code83("Implied PPP conversion rate", "隐含购买力平价转化率"),
    code84("Gross domestic product based on purchasing-power-parity (PPP) valuation of country GDP", "基于国家 GDP 的购买力平价 (PPP) 估值的国内生产总值"),
    code85("Gross domestic product based on purchasing-power-parity (PPP) per capita GDP", "基于购买力平价 (PPP) 人均 GDP 的国内生产总值"),
    code86("Gross domestic product based on purchasing-power-parity (PPP) share of world total", "基于购买力平价 (PPP) 的国内生产总值占世界总量的份额"),
    code87("Commodity Agricultural Raw Materials Index includes Timber, Cotton, Wool, Rubber, and Hides Price Indices", "商品农业原材料指数包括木材、棉花、羊毛、橡胶和生皮价格指数"),
    code88("Rice, 5 percent broken milled white rice, Thailand nominal price quote, US$ per metric tonne", "大米，破碎度为 5% 的精白米，泰国名义报价，每公吨美元"),
    code89("Rapeseed oil, crude, FOB Rotterdam, US$ per metric ton", "菜籽油，原油，FOB 鹿特丹，美元每公吨"),
    code90("Rubber, No.1 Rubber Smoked Sheet, FOB Maylaysian/Singapore, US cents per pound", "橡胶，No.1 Rubber Smoked Sheet，FOB Maylaysian/新加坡，美分每磅"),
    code91("Fish (salmon), Farm Bred Norwegian Salmon, export price, US$ per kilogram", "鱼（鲑鱼），农场养殖的挪威鲑鱼，出口价格，每公斤美元"),
    code92("Hard Sawnwood, Dark Red Meranti, select and better quality, C&F U.K port, US$ per cubic meter", "硬锯木，深红柳桉，精选和更好的品质，C&F 英国港口，美元每立方米"),
    code93("Soft Sawnwood, average export price of Douglas Fir, U.S. Price, US$ per cubic meter", "软锯木，花旗松平均出口价格，美国价格，美元每立方米"),
    code94("Commodity Seafood Index includes Fish (salmon) and Shrimp Price Indices", "商品海鲜指数包括鱼（鲑鱼）和虾价格指数"),
    code95("Shrimp, Frozen shell-on headless, block 16/20 count, Indian origin, C&F Japan, US$ per kilogram", "冷冻带壳去头虾，16/20 块，印度原产，C&F 日本，美元每公斤"),
    code96("Soybean Meal, Chicago Soybean Meal Futures (first contract forward) Minimum 48 percent protein, US$ per metric tonne", "豆粕，芝加哥豆粕期货（第一份远期合约）至少 48% 的蛋白质，每公吨美元"),
    code97("Commodity Softwood Index includes Softwood Sawn and Softwood Logs Price Indices", "商品软木指数包括软木锯材和软木原木价格指数"),
    code98("Soybean Oil, Chicago Soybean Oil Futures (first contract forward) exchange approved grades, US$ per metric tonne", "豆油，芝加哥豆油期货（第一份远期合约）交易所认可等级，美元每公吨"),
    code99("Soybeans, U.S. soybeans, Chicago Soybean futures contract (first contract forward) No. 2 yellow and par, US$ per metric tonne", "大豆、美国大豆、芝加哥大豆期货合约（第一合约远期）2 号黄色和平价，美元每公吨"),
    code100("Sugar, European import price, CIF Europe, US cents per pound", "糖，欧洲进口价格，CIF 欧洲，每磅美分"),
    code101("Sugar, Free Market, Coffee Sugar and Cocoa Exchange (CSCE) contract no.11 nearest future position, US cents per pound", "糖、自由市场、咖啡糖和可可交易所 (CSCE) 11 号最近期货合约，每磅美分"),
    code102("Sugar, U.S. import price, contract no.14 nearest futures position, US cents per pound", "糖，美国进口价格，最近的 14 号合约期货头寸，每磅美分"),
    code103("Commodity Sugar Index includes European, Free market, and U.S. Price Indices", "商品糖指数包括欧洲、自由市场和美国价格指数"),
    code104("Sunflower Oil, US export price from Gulf of Mexico, US$ per metric tonne", "向日葵油，美国墨西哥湾出口价格，美元每公吨"),
    code105("Tea, Mombasa, Kenya, Auction Price, US cents per kilogram", "茶叶，蒙巴萨，肯尼亚，拍卖价，每公斤美分"),
    code106("Commodity Timber Index includes Hardwood and Softwood Price Indices", "商品木材指数包括硬木和软木价格指数"),
    code107("Tin, standard grade, LME spot price, US$ per metric tonne", "锡，标准等级，LME 现货价格，美元每公吨"),
    code108("Uranium, u3o8 restricted price, Nuexco exchange spot, US$ per pound", "铀，u3o8 限价，Nuexco 交易所现货，美元每磅"),
    code109("Commodity Vegetable Oil Index includes Soybean, Soybean Meal, Soybean Oil, Rapeseed Oil, Palm Oil, Sunflower Oil, Olive Oil, Fishmeal, and Groundnut Price Indices", "商品植物油指数包括大豆、豆粕、豆油、菜籽油、棕榈油、葵花籽油、橄榄油、鱼粉和花生价格指数"),
    code110("Wheat, No.1 Hard Red Winter, ordinary protein, FOB Gulf of Mexico, US$ per metric tonne", "小麦，No.1 Hard Red Winter，普通蛋白质，墨西哥湾离岸价，美元每公吨"),
    code111("Wool, coarse, 23 micron, Australian Wool Exchange spot quote, US cents per kilogram", "羊毛，粗，23 微米，澳大利亚羊毛交易所现货报价，每公斤美分"),
    code112("Wool, fine, 19 micron, Australian Wool Exchange spot quote, US cents per kilogram", "羊毛，细，19 微米，澳大利亚羊毛交易所现货报价，每公斤美分"),
    code113("Commodity Wool Index includes Coarse and Fine Wool Price Indices", "商品羊毛指数包括粗羊毛和细羊毛价格指数"),
    code114("Zinc, high grade 98% pure, US$ per metric tonne", "高品位 98% 纯锌，美元每公吨"),
    code115("Volume of imports of goods and services", "货物和服务进口量"),
    code116("Volume of Imports of goods", "货物进口量"),
    code117("Trade volume of goods and services", "货物和服务贸易额"),
    code118("Terms of trade of goods and services", "货物和服务贸易条款"),
    code119("Terms of trade of goods", "货物贸易条款"),
    code120("Volume of exports of goods and services", "货物和服务出口量"),
    code121("Volume of exports of goods", "货物出口量"),
    code122("Export price of manufactures", "制成品出口价格");


    private final String src;
    private final String cn;

    public static String getCn(String code) {
        for (IMFCodeTransEnum ele : values()) {
            if (ele.getSrc().equals(code)) return ele.getCn();
        }
        return null;
    }
}
