package com.idc.common.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum IMFCountryTransEnum {
    country1("New Zealand", "新西兰"),
    country2("Fiji", "斐济"),
    country3("Guadeloupe", "瓜德罗普岛"),
    country4("Wallis and Futuna Islands", "瓦利斯群岛和富图纳群岛"),
    country5("Low-Income Developing Countries (median", "低收入发展中国家（中位数）"),
    country6("Sudan", "苏丹"),
    country7("Gambia, The", "冈比亚"),
    country8("Central and Eastern Europe", "中东欧"),
    country9("Malaysia", "马来西亚"),
    country10("Mayotte", "马约特岛"),
    country11("Economic Community of West African States", "西非国家经济共同体"),
    country12("Middle East, North Africa, Afghanistan, and Pakistan", "中东、北非、阿富汗和巴基斯坦"),
    country13("Guinea-Bissau", "几内亚比绍"),
    country14("Senegal", "塞内加尔"),
    country15("Togo", "多哥"),
    country16("Southeast Asia", "东南亚"),
    country17("Ireland", "爱尔兰"),
    country18("Falkland Islands", "福克兰群岛"),
    country19("Iran", "伊朗"),
    country20("Qatar", "卡塔尔"),
    country21("Burundi", "布隆迪"),
    country22("Iraq", "伊拉克"),
    country23("Equatorial Guinea", "赤道几内亚"),
    country24("Thailand", "泰国"),
    country25("World", "世界"),
    country26("Emerging Markets", "新兴市场"),
    country27("Aruba", "阿鲁巴岛"),
    country28("Iceland", "冰岛"),
    country29("World", "世界"),
    country30("Belgium", "比利时"),
    country31("Israel", "以色列"),
    country32("Kuwait", "科威特"),
    country33("Benin", "贝宁"),
    country34("Euro area", "欧元区"),
    country35("Italy", "意大利"),
    country36("Pakistan", "巴基斯坦"),
    country37("Burkina Faso", "布基纳法索"),
    country38("Panama", "巴拿马"),
    country39("Singapore", "新加坡"),
    country40("Ukraine", "乌克兰"),
    country41("Emerging and Developing Asia", "新兴和发展中亚洲"),
    country42("Switzerland", "瑞士"),
    country43("Djibouti", "吉布提"),
    country44("Reunion", "团圆"),
    country45("Low-Income Developing Countries", "低收入发展中国家"),
    country46("Channel Islands", "海峡群岛"),
    country47("Chile", "智利"),
    country48("Low-Income Developing Sub-Saharan Africa", "低收入发展中撒哈拉以南非洲"),
    country49("China, People's Republic of", "中国，中华人民共和国"),
    country50("Croatia", "克罗地亚"),
    country51("Tajikistan", "塔吉克斯坦"),
    country52("Vietnam", "越南"),
    country53("Low-Income Developing Others", "低收入发展中国家"),
    country54("World", "世界"),
    country55("Saint Helena", "圣海伦娜"),
    country56("Bangladesh", "孟加拉国"),
    country57("Zimbabwe", "津巴布韦"),
    country58("All countries - Fiscal Rules & Fiscal Councils", "所有国家 - 财政规则和财政委员会"),
    country59("Bulgaria", "保加利亚"),
    country60("Commonwealth of Independent States", "独立国家联合体"),
    country61("Resource-intensive countries", "资源密集型国家"),
    country62("European Union", "欧洲联盟"),
    country63("Côte d'Ivoire", "科特迪瓦"),
    country64("Other advanced economies", "其他发达经济体"),
    country65("Tokelau", "托克劳"),
    country66("Turkmenistan", "土库曼斯坦"),
    country67("Grenada", "格林纳达"),
    country68("Greece", "希腊"),
    country69("Pitcairn", "皮特凯恩"),
    country70("Haiti", "海地"),
    country71("Frontier LIDCs (median", "前沿低收入发展中国家（中位数）"),
    country72("Greenland", "格陵兰"),
    country73("Afghanistan", "阿富汗"),
    country74("Bahamas, The", "巴哈马群岛"),
    country75("Africa (Region", "非洲（地区）"),
    country76("Bahrain", "巴林"),
    country77("Africa (Analytical", "非洲（分析）"),
    country78("Caribbean and Pacific Islands", "加勒比和太平洋岛屿"),
    country79("Svalbard and Jan Mayen Islands", "斯瓦尔巴群岛和扬马延群岛"),
    country80("Oil-importing countries", "石油进口国"),
    country81("Dominica", "多米尼克"),
    country82("Timor-Leste", "东帝汶"),
    country83("Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那"),
    country84("Hungary", "匈牙利"),
    country85("Low Income Developing Countries", "低收入发展中国家"),
    country86("East African Community", "东非共同体"),
    country87("Angola", "安哥拉"),
    country88("Samoa", "萨摩亚"),
    country89("France", "法国"),
    country90("Western Hemisphere Group", "西半球集团"),
    country91("Countries in fragile and conflict-affected situations", "处于脆弱和受冲突影响局势中的国家"),
    country92("Rest", "休息"),
    country93("Namibia", "纳米比亚"),
    country94("Peru", "秘鲁"),
    country95("North Africa", "北非"),
    country96("Europe", "欧洲"),
    country97("Denmark", "丹麦"),
    country98("Guatemala", "危地马拉"),
    country99("Faeroe Islands", "法罗群岛"),
    country100("Solomon Islands", "所罗门群岛"),
    country101("Sierra Leone", "塞拉利昂"),
    country102("Emerging and Middle-Income Asia", "亚洲新兴和中等收入国家"),
    country103("Non-Oil Slow", "非油慢"),
    country104("Anguilla", "安圭拉"),
    country105("French Guiana", "法属圭亚那"),
    country106("El Salvador", "萨尔瓦多"),
    country107("Guam", "关岛"),
    country108("Micronesia, Fed. States of", "密克罗尼西亚，美联储。的国家"),
    country109("Dominican Republic", "多明尼加共和国"),
    country110("Central America", "中美洲"),
    country111("Cameroon", "喀麦隆"),
    country112("Guyana", "圭亚那"),
    country113("Low-Income Developing Asia", "低收入发展中亚洲"),
    country114("Macao SAR", "澳门特别行政区"),
    country115("Major advanced economies (G7", "主要发达经济体（G7）"),
    country116("Tonga", "汤加"),
    country117("Low-Income Countries", "低收入国家"),
    country118("Emerging Asia excl Japan incl NIEs", "新兴亚洲，不包括日本，包括 NIEs"),
    country119("New Caledonia", "新喀里多尼亚"),
    country120("South America", "南美洲"),
    country121("San Marino", "圣马力诺"),
    country122("Eritrea", "厄立特里亚"),
    country123("Morocco", "摩洛哥"),
    country124("SSA excluding Zimbabwe", "不包括津巴布韦的 SSA"),
    country125("Belarus", "白俄罗斯"),
    country126("WAEMU", "西非机车联盟"),
    country127("Belize", "伯利兹"),
    country128("Philippines", "菲律宾"),
    country129("European Union", "欧洲联盟"),
    country130("Congo, Dem. Rep. of the", "刚果民主共和国众议员"),
    country131("Congo, Republic of", "刚果共和国"),
    country132("Western Sahara", "撒哈拉沙漠西部"),
    country133("Uruguay", "乌拉圭"),
    country134("Cook Islands", "库克群岛"),
    country135("Commonwealth of Independent States and Mongolia", "独立国家联合体和蒙古"),
    country136("High Inflation Countries", "高通胀国家"),
    country137("Comoros", "科摩罗"),
    country138("Colombia", "哥伦比亚"),
    country139("Non-resource-intensive countires", "非资源密集型国家"),
    country140("United States", "美国"),
    country141("Spain", "西班牙"),
    country142("G-20 Emerging", "20 国集团新兴市场"),
    country143("Estonia", "爱沙尼亚"),
    country144("Non-Oil Middle Income", "非石油中等收入"),
    country145("EM and dev econ incl sel adv econ", "EM 和 dev econ incl sel adv econ"),
    country146("Bermuda", "百慕大"),
    country147("Middle East and North Africa", "中东和北非"),
    country148("Somalia", "索马里"),
    country149("G-20 Advanced", "G-20高级"),
    country150("Advanced Economies", "发达经济体"),
    country151("Vanuatu", "瓦努阿图"),
    country152("Albania", "阿尔巴尼亚"),
    country153("Ethiopia", "埃塞俄比亚"),
    country154("Monaco", "摩纳哥"),
    country155("Emerging Market and Developing Economies", "新兴市场和发展中经济体"),
    country156("Pacific Islands", "太平洋岛屿"),
    country157("Niger", "尼日尔"),
    country158("Lao P.D.R", "老挝人民民主共和国"),
    country159("Emerging G-20", "新兴 20 国集团"),
    country160("Landlocked", "内陆"),
    country161("Africa", "非洲"),
    country162("Bonaire", "博内尔岛"),
    country163("Cabo Verde", "佛得角"),
    country164("World", "世界"),
    country165("Moldova", "摩尔多瓦"),
    country166("Madagascar", "马达加斯加"),
    country167("Saint-Pierre and Miquelon", "圣皮埃尔和密克隆"),
    country168("Positive growth", "正增长"),
    country169("Middle East (Analytical", "中东（分析）"),
    country170("Lebanon", "黎巴嫩"),
    country171("Liberia", "利比里亚"),
    country172("Bolivia", "玻利维亚"),
    country173("Maldives", "马尔代夫"),
    country174("Europe", "欧洲"),
    country175("Libya", "利比亚"),
    country176("Europe", "欧洲"),
    country177("Nigeria", "尼日利亚"),
    country178("Saint Lucia", "圣卢西亚"),
    country179("Adv econ excl US, Euro, Japan", "Adv econ excl US, Euro, 日本"),
    country180("Eastern Caribbean Currency Union", "东加勒比货币联盟"),
    country181("Andorra", "安道尔"),
    country182("Middle East (Region", "中东（地区）"),
    country183("Romania", "罗马尼亚"),
    country184("Middle East and Central Asia", "中东和中亚"),
    country185("Costa Rica", "哥斯达黎加"),
    country186("Mexico", "墨西哥"),
    country187("Serbia", "塞尔维亚"),
    country188("Kazakhstan", "哈萨克斯坦"),
    country189("Kosovo", "科索沃"),
    country190("Non European Union", "非欧盟"),
    country191("Trinidad and Tobago", "特立尼达和多巴哥"),
    country192("Oil Producers", "产油国"),
    country193("Low Income", "低收入"),
    country194("Palau", "帕劳"),
    country195("Saint Martin", "圣马丁"),
    country196("Sub-Saharan Africa", "撒哈拉以南非洲"),
    country197("Non-Oil Medium", "非油介质"),
    country198("South Sudan, Republic of", "南苏丹共和国"),
    country199("Sub-Saharan Africa (Region", "撒哈拉以南非洲（地区）"),
    country200("Nicaragua", "尼加拉瓜"),
    country201("Tunisia", "突尼斯"),
    country202("Brazil", "巴西"),
    country203("Türkiye, Republic of", "土耳其共和国"),
    country204("Sub-Saharan Africa (Region", "撒哈拉以南非洲（地区）"),
    country205("Barbados", "巴巴多斯"),
    country206("Tuvalu", "图瓦卢"),
    country207("Jamaica", "牙买加"),
    country208("Niue", "纽埃"),
    country209("South Africa", "南非"),
    country210("Brunei Darussalam", "文莱达鲁萨兰国"),
    country211("Asia and Pacific", "亚太地区"),
    country212("Papua New Guinea", "巴布亚新几内亚"),
    country213("Prominent gender budgeting countries covered in the surveys", "调查涵盖的主要性别预算编制国家"),
    country214("São Tomé and Príncipe", "圣多美和普林西比"),
    country215("Marshall Islands", "马绍尔群岛"),
    country216("Cuba", "古巴"),
    country217("Other gender budgeting countries covered in the surveys", "调查中涵盖的其他性别预算编制国家"),
    country218("Curacao", "库拉索"),
    country219("Middle-income countries", "中等收入国家"),
    country220("Taiwan Province of China", "中国台湾省"),
    country221("MDRI countries", "多边倡议国家"),
    country222("Poland", "波兰"),
    country223("Oman", "阿曼"),
    country224("Suriname", "苏里南"),
    country225("United Arab Emirates", "阿拉伯联合酋长国"),
    country226("Kenya", "肯尼亚"),
    country227("Argentina", "阿根廷"),
    country228("Armenia", "亚美尼亚"),
    country229("Uzbekistan", "乌兹别克斯坦"),
    country230("Bhutan", "不丹"),
    country231("Non G-20", "非 G-20"),
    country232("Catergory IV", "第四类"),
    country233("Catergory III", "第三类"),
    country234("CFA Franc Zone", "非洲金融共同体法郎区"),
    country235("Catergory II", "第二类"),
    country236("ASEAN-5", "东盟五国"),
    country237("Catergory I", "第一类"),
    country238("Countries eligible for PRGF", "有资格获得 PRGF 的国家"),
    country239("Netherlands", "荷兰人"),
    country240("Slovak Republic", "斯洛伐克共和国"),
    country241("Advanced G-20", "高级G-20"),
    country242("Slovenia", "斯洛文尼亚"),
    country243("Emerging and Middle-Income Europe", "新兴和中等收入欧洲"),
    country244("Catergory VI", "第六类"),
    country245("Catergory V", "第五类"),
    country246("Asia & Pacific Group", "亚太集团"),
    country247("American Samoa", "美属萨摩亚"),
    country248("CEMAC", "中美经济共同体"),
    country249("Sweden", "瑞典"),
    country250("High Income Countries (median", "高收入国家（中位数）"),
    country251("Oil-exporting countries excluding Nigeria", "除尼日利亚外的石油出口国"),
    country252("African Regional Economic Outlook", "非洲区域经济展望"),
    country253("North Macedonia", "北马其顿"),
    country254("Low-income countries", "低收入国家"),
    country255("Liechtenstein", "列支敦士登"),
    country256("Algeria", "阿尔及利亚"),
    country257("Low-Income Developing Oil Producers", "低收入发展中石油生产国"),
    country258("Russian Federation", "俄罗斯联邦"),
    country259("North America", "北美"),
    country260("Antigua and Barbuda", "安提瓜和巴布达"),
    country261("Eswatini", "史瓦帝尼"),
    country262("Export earnings: nonfuel", "出口收入：非燃料"),
    country263("Tanzania", "坦桑尼亚"),
    country264("Kyrgyz Republic", "吉尔吉斯共和国"),
    country265("COMESA (SSA members", "COMESA（SSA 成员）"),
    country266("None G-7", "无 G-7"),
    country267("European Group", "欧洲集团"),
    country268("Puerto Rico", "波多黎各"),
    country269("World", "世界"),
    country270("Korea, Dem. People's Rep. of", "韩国，民主党。人民共和国"),
    country271("Sint Maarten", "圣马丁岛"),
    country272("Mali", "马里"),
    country273("Botswana", "博茨瓦纳"),
    country274("Cambodia", "柬埔寨"),
    country275("Indonesia", "印度尼西亚"),
    country276("Portugal", "葡萄牙"),
    country277("Malta", "马耳他"),
    country278("Cayman Islands", "开曼群岛"),
    country279("Paraguay", "巴拉圭"),
    country280("Cyprus", "塞浦路斯"),
    country281("Seychelles", "塞舌尔"),
    country282("Rwanda", "卢旺达"),
    country283("Australia", "澳大利亚"),
    country284("Austria", "奥地利"),
    country285("Sri Lanka", "斯里兰卡"),
    country286("Countries without conventional exchange rate pegs", "没有传统汇率挂钩的国家"),
    country287("Gabon", "加蓬"),
    country288("Syria", "叙利亚"),
    country289("Czech Republic", "捷克共和国"),
    country290("Norway", "挪威"),
    country291("Asia", "亚洲"),
    country292("Myanmar", "缅甸"),
    country293("Kiribati", "基里巴斯"),
    country294("Non-Oil Low Income", "非石油低收入"),
    country295("Yemen", "也门"),
    country296("G-7", "G-7"),
    country297("Montenegro", "黑山"),
    country298("Mongolia", "蒙古"),
    country299("Nepal", "尼泊尔"),
    country300("Euro area", "欧元区"),
    country301("Northern Mariana Islands", "北马里亚纳群岛"),
    country302("Latin America and the Caribbean", "拉丁美洲和加勒比地区"),
    country303("Western Hemisphere", "西半球"),
    country304("Middle East and Central Asia Group", "中东和中亚集团"),
    country305("SSA excluding Nigeria and South Africa", "SSA，不包括尼日利亚和南非"),
    country306("United Kingdom", "英国"),
    country307("MICs excluding Nigeria and South Africa", "中等收入国家，不包括尼日利亚和南非"),
    country308("West Bank and Gaza", "约旦河西岸和加沙"),
    country309("Euro Area", "欧元区"),
    country310("Sub-Saharan Africa, excluding South Sudan", "撒哈拉以南非洲，不包括南苏丹"),
    country311("Mozambique", "莫桑比克"),
    country312("Emerging Market and Middle-Income Economies", "新兴市场和中等收入经济体"),
    country313("Other Groups", "其他团体"),
    country314("Holy See", "教廷"),
    country315("Nauru", "瑙鲁"),
    country316("Countries with conventional exchange rate pegs", "采用传统汇率挂钩的国家"),
    country317("World", "世界"),
    country318("Identified as gender budgeting country in IMF regional survey", "在国际货币基金组织区域调查中被确定为性别预算国家"),
    country319("East African Community", "东非共同体"),
    country320("Azerbaijan", "阿塞拜疆"),
    country321("International Organizations", "国际组织"),
    country322("Georgia", "乔治亚州"),
    country323("East Asia", "东亚"),
    country324("Australia and New Zealand", "澳大利亚和新西兰"),
    country325("Saint Kitts and Nevis", "圣基茨和尼维斯"),
    country326("Coastal", "沿海"),
    country327("Western Europe", "西欧"),
    country328("Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯"),
    country329("Mauritania", "毛里塔尼亚"),
    country330("Oil-importing countries excluding South Africa", "不包括南非的石油进口国"),
    country331("French Polynesia", "法属波利尼西亚"),
    country332("SACU", "SACU"),
    country333("Emerging Asia", "新兴亚洲"),
    country334("Oil-exporting countries", "石油输出国"),
    country335("SADC", "南部非洲发展共同体"),
    country336("Montserrat", "蒙特塞拉特"),
    country337("Zambia", "赞比亚"),
    country338("Korea, Republic of", "大韩民国"),
    country339("Ecuador", "厄瓜多尔"),
    country340("Non-oil", "无油"),
    country341("Venezuela", "委内瑞拉"),
    country342("Inflation exceeding growth", "通胀超过增长"),
    country343("Ghana", "加纳"),
    country344("World", "世界"),
    country345("Emerging and Middle-Income Latin America", "拉丁美洲新兴市场和中等收入国家"),
    country346("LICs excluding low income countries in fragile and conflict-affected situations", "低收入国家不包括处于脆弱和受冲突影响局势中的低收入国家"),
    country347("Emerging and Developing Europe", "新兴和发展中欧洲"),
    country348("Martinique", "马提尼克岛"),
    country349("Emerging Market", "新兴市场"),
    country350("Emerging market and developing economies", "新兴市场和发展中经济体"),
    country351("Emerging and Developing Countries", "新兴和发展中国家"),
    country352("Gibraltar", "直布罗陀"),
    country353("Western Hemisphere (Region", "西半球（地区）"),
    country354("Emerging and Middle-Income Middle East and North Africa and Pakistan", "中东、北非和巴基斯坦的新兴和中等收入国家"),
    country355("Hong Kong SAR", "香港特别行政区"),
    country356("G-20", "G-20"),
    country357("Export earnings: fuel", "出口收入：燃料"),
    country358("Central African Republic", "中非共和国"),
    country359("Lesotho", "莱索托"),
    country360("Mauritius", "毛里求斯"),
    country361("Jordan", "约旦"),
    country362("Guinea", "几内亚"),
    country363("Other Advanced", "其他进阶"),
    country364("British Virgin Islands", "英属维尔京群岛"),
    country365("Eastern Europe", "东欧洲"),
    country366("Canada", "加拿大"),
    country367("Central Asia and the Caucasus", "中亚和高加索"),
    country368("Turks and Caicos Islands", "特克斯和凯科斯群岛"),
    country369("Isle of Man", "马恩岛"),
    country370("Chad", "乍得"),
    country371("All countries - Global Debt", "所有国家 - 全球债务"),
    country372("Other countries", "其他国家"),
    country373("Non-Oil High Income", "非石油高收入"),
    country374("India", "印度"),
    country375("African Group", "非洲集团"),
    country376("South Asia", "南亚"),
    country377("Advanced economies", "发达经济体"),
    country378("Saudi Arabia", "沙特阿拉伯"),
    country379("Japan", "日本"),
    country380("Lithuania", "立陶宛"),
    country381("Middle East and Central Asia", "中东和中亚"),
    country382("Caribbean", "加勒比地区"),
    country383("Advanced Economies", "发达经济体"),
    country384("Low-Income Developing Latin America", "拉丁美洲低收入发展中国家"),
    country385("Malawi", "马拉维"),
    country386("Finland", "芬兰"),
    country387("Luxembourg", "卢森堡"),
    country388("Uganda", "乌干达"),
    country389("Advanced Economies", "发达经济体"),
    country390("Germany", "德国"),
    country391("Egypt", "埃及"),
    country392("Latvia", "拉脱维亚"),
    country393("Non-Oil Fast", "非油快"),
    country394("United States Virgin Islands", "美属维尔京群岛"),
    country395("Honduras", "洪都拉斯");

    private final String src;
    private final String cn;

    public static String getCn(String code) {
        for (IMFCountryTransEnum ele : values()) {
            if (ele.getSrc().equals(code)) return ele.getCn();
        }
        return null;
    }
}
