package com.idc.common.constants;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum IMFCodeEnum {
    BCA("BCA","Current account balance"),
    BCA_NGDPD("BCA_NGDPD","Current account balance"),
    BF("BF","Financial account balance"),
    BFD("BFD","Direct investment, net"),
    BFF("BFF","Financial derivatives, net"),
    BFO("BFO","Other investment, net"),
    BFP("BFP","Portfolio investment, net"),
    BFRA("BFRA","Change in reserves"),
    BM("BM","Imports of goods and services"),
    BX("BX","Exports of goods and services"),
    D("D","External debt, total"),
    D_BX("D_BX","External debt, total"),
    D_NGDPD("D_NGDPD","External debt, total"),
    DS("DS","External debt, total debt service"),
    DS_BX("DS_BX","External debt, total debt service"),
    DS_NGDPD("DS_NGDPD","External debt, total debt service"),
    DSI("DSI","External debt, total debt service, interest"),
    DSI_BX("DSI_BX","External debt, total debt service, interest"),
    DSI_NGDPD("DSI_NGDPD","External debt, total debt service, interest"),
    DSP("DSP","External debt, total debt service, amortization"),
    DSP_BX("DSP_BX","External debt, total debt service, amortization"),
    DSP_NGDPD("DSP_NGDPD","External debt, total debt service, amortization"),
    GGR("GGR","General government revenue"),
    GGR_NGDP("GGR_NGDP","General government revenue"),
    GGSB("GGSB","General government structural balance"),
    GGSB_NPGDP("GGSB_NPGDP","General government structural balance"),
    GGX("GGX","General government total expenditure"),
    GGX_NGDP("GGX_NGDP","General government total expenditure"),
    GGXCNL("GGXCNL","General government net lending/borrowing"),
    GGXCNL_NGDP("GGXCNL_NGDP","General government net lending/borrowing"),
    GGXONLB("GGXONLB","General government primary net lending/borrowing"),
    GGXONLB_NGDP("GGXONLB_NGDP","General government primary net lending/borrowing"),
    GGXWDG("GGXWDG","General government gross debt"),
    GGXWDG_NGDP("GGXWDG_NGDP","General government gross debt"),
    GGXWDN("GGXWDN","General government net debt"),
    GGXWDN_NGDP("GGXWDN_NGDP","General government net debt"),
    LE("LE","Employment"),
    LP("LP","Population"),
    LUR("LUR","Unemployment rate"),
    NGAP_NPGDP("NGAP_NPGDP","Output gap"),
    NGDP("NGDP","Gross domestic product, current prices"),
    NGDP_D("NGDP_D","Gross domestic product, deflator"),
    NGDP_FY("NGDP_FY","Gross domestic product corresponding to fiscal year, current prices"),
    NGDP_R("NGDP_R","Gross domestic product, constant prices"),
    NGDP_RPCH("NGDP_RPCH","Gross domestic product, constant prices"),
    NGDP_RPCHMK("NGDP_RPCHMK","Gross domestic product, constant prices"),
    NGDPD("NGDPD","Gross domestic product, current prices"),
    NGDPDPC("NGDPDPC","Gross domestic product per capita, current prices"),
    NGDPPC("NGDPPC","Gross domestic product per capita, current prices"),
    NGDPRPC("NGDPRPC","Gross domestic product per capita, constant prices"),
    NGSD_NGDP("NGSD_NGDP","Gross national savings"),
    NID_NGDP("NID_NGDP","Investment"),
    PALLFNFW("PALLFNFW","Commodity Price Index includes both Fuel and Non-Fuel Price Indices"),
    PALUM("PALUM","Aluminum, 99.5% minimum purity, LME spot price, CIF UK ports, US$ per metric tonne"),
    PBANSOP("PBANSOP","Bananas, Central American and Ecuador, FOB U.S. Ports, US$ per metric tonne"),
    PBARL("PBARL","Barley, Canadian no.1 Western Barley, spot price, US$ per metric tonne"),
    PBEEF("PBEEF","Beef, Australian and New Zealand 85% lean fores, FOB U.S. import price, US cents per pound"),
    PBEVEW("PBEVEW","Commodity Beverage Price Index includes Coffee, Tea, and Cocoa"),
    PCEREW("PCEREW","Commodity Cereals Price Index includes Wheat, Maize (Corn), Rice, and Barley"),
    PCOALAU("PCOALAU","Coal, Australian thermal coal, 1200- btu/pound, less than 1% sulfur, 14% ash, FOB Newcastle/Port Kembla, US$ per metric tonne"),
    PCOALSA("PCOALSA","Coal, South African export price, US$ per metric tonne"),
    PCOALW("PCOALW","Commodity Coal Price Index includes Australian and South African Coal"),
    PCOCO("PCOCO","Cocoa beans, International Cocoa Organization cash price, CIF US and European ports, US$ per metric tonne"),
    PCOFFOTM("PCOFFOTM","Coffee, Other Mild Arabicas, International Coffee Organization New York cash price, ex-dock New York, US cents per pound"),
    PCOFFROB("PCOFFROB","Coffee, Robusta, International Coffee Organization New York cash price, ex-dock New York, US cents per pound"),
    PCOFFW("PCOFFW","Commodity Coffee Price Index includes Other Mild Arabicas and Robusta"),
    PCOPP("PCOPP","Copper, grade A cathode, LME spot price, CIF European ports, US$ per metric tonne"),
    PCOTTIND("PCOTTIND","Cotton, Cotton Outlook `A Index`, Middling 1-3/32 inch staple, CIF Liverpool, US cents per pound"),
    PCPI("PCPI","Inflation, average consumer prices"),
    PCPIE("PCPIE","Inflation, end of period consumer prices"),
    PCPIEPCH("PCPIEPCH","Inflation, end of period consumer prices"),
    PCPIPCH("PCPIPCH","Inflation, average consumer prices"),
    PFANDBW("PFANDBW","Commodity Food and Beverage Price Index includes Food and Beverage Price Indices"),
    PFISH("PFISH","Fishmeal, Peru Fish meal/pellets 65% protein, CIF, US$ per metric tonne"),
    PFOODW("PFOODW","Commodity Food Price Index includes Cereal, Vegetable Oils, Meat, Seafood, Sugar, Bananas, and Oranges Price Indices"),
    PGNUTS("PGNUTS","Groundnuts (peanuts), 40/50 (40 to 50 count per ounce), cif Argentina, US$ per metric tonne"),
    PHARDW("PHARDW","Commodity Hardwood Price Index includes Hardwood Logs and Hardwood Sawn Price Indices"),
    PHIDE("PHIDE","Hides, Heavy native steers, over 53 pounds, wholesale dealer`s price, US cents per pound"),
    PINDUW("PINDUW","Commodity Industrial Inputs Price Index includes Agricultural Raw Materials and Metals Price Indices"),
    PIORECR("PIORECR","Iron Ore, China import Iron Ore Fines 62% FE spot (CFR Tianjin port) US$ per metric ton"),
    PLAMB("PLAMB","Lamb, frozen carcass Smithfield London, US cents per pound"),
    PLEAD("PLEAD","Lead, 99.97% pure, LME spot price, CIF European Ports, US$ per metric tonne"),
    PLOGORE("PLOGORE","Soft Logs, Average Export price from the U.S. for Douglas Fir, US$ per cubic meter"),
    PLOGSK("PLOGSK","Hard Logs, Best quality Malaysian meranti, import price Japan, US$ per cubic meter"),
    PMAIZMT("PMAIZMT","Maize (corn), U.S. No.2 Yellow, FOB Gulf of Mexico, U.S. price, US$ per metric tonne"),
    PMEATW("PMEATW","Commodity Meat Price Index includes Beef, Lamb, Swine (pork), and Poultry Price Indices"),
    PMETAW("PMETAW","Commodity Metals Price Index includes Copper, Aluminum, Iron Ore, Tin, Nickel, Zinc, Lead, and Uranium Price Indices"),
    PNFUELW("PNFUELW","Commodity Non-Fuel Price Index includes Food and Beverages and Industrial Inputs Price Indices"),
    PNGASEU("PNGASEU","Natural Gas, Russian Natural Gas border price in Germany, US$ per million metric British thermal units of gas"),
    PNGASJP("PNGASJP","Natural Gas, Indonesian Liquified Natural Gas in Japan, US$ per million metric British thermal units of liquid"),
    PNGASUS("PNGASUS","Natural Gas, Natural Gas spot price at the Henry Hub terminal in Louisiana, US$ per million metric British thermal units of gas"),
    PNGASW("PNGASW","Commodity Natural Gas Price Index includes European, Japanese, and American Natural Gas Price Indices"),
    PNICK("PNICK","Nickel, melting grade, LME spot price, CIF European ports, US$ per metric tonne"),
    PNRGW("PNRGW","Commodity Fuel (energy) Index includes Crude oil (petroleum), Natural Gas, and Coal Price Indices"),
    POILAPSP("POILAPSP","Crude Oil (petroleum), simple average of three spot prices; Dated Brent, West Texas Intermediate, and the Dubai Fateh, US$ per barrel"),
    POILAPSPW("POILAPSPW","Crude Oil (petroleum), Price index simple average of three spot prices (APSP); Dated Brent, West Texas Intermediate, and the Dubai Fateh"),
    POILBRE("POILBRE","Crude Oil (petroleum),  Dated Brent, light blend 38 API, fob U.K., US$ per barrel"),
    POILDUB("POILDUB","Oil; Dubai, medium, Fateh 32 API, fob Dubai Crude Oil (petroleum), Dubai Fateh Fateh 32 API, US$ per barrel"),
    POILWTI("POILWTI","Crude Oil (petroleum), West Texas Intermediate 40 API, Midland Texas, US$ per barrel"),
    POLVOIL("POLVOIL","Olive Oil, extra virgin less than 1% free fatty acid, ex-tanker price U.K., US$ per metric tonne"),
    PORANG("PORANG","Oranges, miscellaneous oranges French import price, US$ per metric tonne"),
    PPOIL("PPOIL","Palm oil, Malaysia Palm Oil Futures (first contract forward) 4-5 percent FFA, US$ per metric tonne"),
    PPORK("PPORK","Swine (pork), 51-52% lean Hogs, U.S. price, US cents per pound"),
    PPOULT("PPOULT","Poultry (chicken), Whole bird spot price, Georgia docks, US cents per pound"),
    PPPEX("PPPEX","Implied PPP conversion rate"),
    PPPGDP("PPPGDP","Gross domestic product based on purchasing-power-parity (PPP) valuation of country GDP"),
    PPPPC("PPPPC","Gross domestic product based on purchasing-power-parity (PPP) per capita GDP"),
    PPPSH("PPPSH","Gross domestic product based on purchasing-power-parity (PPP) share of world total"),
    PRAWMW("PRAWMW","Commodity Agricultural Raw Materials Index includes Timber, Cotton, Wool, Rubber, and Hides Price Indices"),
    PRICENPQ("PRICENPQ","Rice, 5 percent broken milled white rice, Thailand nominal price quote, US$ per metric tonne"),
    PROIL("PROIL","Rapeseed oil, crude, FOB Rotterdam, US$ per metric ton"),
    PRUBB("PRUBB","Rubber, No.1 Rubber Smoked Sheet, FOB Maylaysian/Singapore, US cents per pound"),
    PSALM("PSALM","Fish (salmon), Farm Bred Norwegian Salmon, export price, US$ per kilogram"),
    PSAWMAL("PSAWMAL","Hard Sawnwood, Dark Red Meranti, select and better quality, C&F U.K port, US$ per cubic meter"),
    PSAWORE("PSAWORE","Soft Sawnwood, average export price of Douglas Fir, U.S. Price, US$ per cubic meter"),
    PSEAFW("PSEAFW","Commodity Seafood Index includes Fish (salmon) and Shrimp Price Indices"),
    PSHRI("PSHRI","Shrimp, Frozen shell-on headless, block 16/20 count, Indian origin, C&F Japan, US$ per kilogram"),
    PSMEA("PSMEA","Soybean Meal, Chicago Soybean Meal Futures (first contract forward) Minimum 48 percent protein, US$ per metric tonne"),
    PSOFTW("PSOFTW","Commodity Softwood Index includes Softwood Sawn and Softwood Logs Price Indices"),
    PSOIL("PSOIL","Soybean Oil, Chicago Soybean Oil Futures (first contract forward) exchange approved grades, US$ per metric tonne"),
    PSOYB("PSOYB","Soybeans, U.S. soybeans, Chicago Soybean futures contract (first contract forward) No. 2 yellow and par, US$ per metric tonne"),
    PSUGAEEC("PSUGAEEC","Sugar, European import price, CIF Europe, US cents per pound"),
    PSUGAISA("PSUGAISA","Sugar, Free Market, Coffee Sugar and Cocoa Exchange (CSCE) contract no.11 nearest future position, US cents per pound"),
    PSUGAUSA("PSUGAUSA","Sugar, U.S. import price, contract no.14 nearest futures position, US cents per pound"),
    PSUGAW("PSUGAW","Commodity Sugar Index includes European, Free market, and U.S. Price Indices"),
    PSUNO("PSUNO","Sunflower Oil, US export price from Gulf of Mexico, US$ per metric tonne"),
    PTEA("PTEA","Tea, Mombasa, Kenya, Auction Price, US cents per kilogram"),
    PTIMBW("PTIMBW","Commodity Timber Index includes Hardwood and Softwood Price Indices"),
    PTIN("PTIN","Tin, standard grade, LME spot price, US$ per metric tonne"),
    PURAN("PURAN","Uranium, u3o8 restricted price, Nuexco exchange spot, US$ per pound"),
    PVOILW("PVOILW","Commodity Vegetable Oil Index includes Soybean, Soybean Meal, Soybean Oil, Rapeseed Oil, Palm Oil, Sunflower Oil, Olive Oil, Fishmeal, and Groundnut Price Indices"),
    PWHEAMT("PWHEAMT","Wheat, No.1 Hard Red Winter, ordinary protein, FOB Gulf of Mexico, US$ per metric tonne"),
    PWOOLC("PWOOLC","Wool, coarse, 23 micron, Australian Wool Exchange spot quote, US cents per kilogram"),
    PWOOLF("PWOOLF","Wool, fine, 19 micron, Australian Wool Exchange spot quote, US cents per kilogram"),
    PWOOLW("PWOOLW","Commodity Wool Index includes Coarse and Fine Wool Price Indices"),
    PZINC("PZINC","Zinc, high grade 98% pure, US$ per metric tonne"),
    TM_RPCH("TM_RPCH","Volume of imports of goods and services"),
    TMG_RPCH("TMG_RPCH","Volume of Imports of goods"),
    TRADEPCH("TRADEPCH","Trade volume of goods and services"),
    TTPCH("TTPCH","Terms of trade of goods and services"),
    TTTPCH("TTTPCH","Terms of trade of goods"),
    TX_RPCH("TX_RPCH","Volume of exports of goods and services"),
    TXG_RPCH("TXG_RPCH","Volume of exports of goods"),
    TXGM_D("TXGM_D","Export price of manufactures"),
    TXGM_DPCH("TXGM_DPCH","Export price of manufactures"),
    NGDPRPPPPC("NGDPRPPPPC","Gross domestic product per capita, constant prices");



    private final String code;
    private final String desc;

    public static String getValue(String code) {
        for (IMFCodeEnum ele : values()) {
            if (ele.getCode().equals(code)) return ele.getDesc();
        }
        return null;
    }
}
